require("cole.plugins")
require("cole.core.options")
require("cole.core.keymaps")
require("cole.core.colorscheme")
require("cole.core.autocmds")
require("cole.plugins.cmp")
require("cole.plugins.lsp.mason")
require("cole.plugins.lsp.lspconfig")
require("cole.plugins.tresitter")
require("cole.plugins.telescope")
require("cole.plugins.lualine")

